// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGNd_HXMW2Ur86GKMqekLjKtZdHjfR8mk',
    appId: '1:379044413189:web:eee4ef71aa11fd7959c16c',
    messagingSenderId: '379044413189',
    projectId: 'flutterpushnotification-2ebe9',
    authDomain: 'flutterpushnotification-2ebe9.firebaseapp.com',
    storageBucket: 'flutterpushnotification-2ebe9.appspot.com',
    measurementId: 'G-MX6LPFN370',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzF8P4020AWgODVrN-sjhrZnIkAPiKbFs',
    appId: '1:379044413189:android:2adfb571adf4177959c16c',
    messagingSenderId: '379044413189',
    projectId: 'flutterpushnotification-2ebe9',
    storageBucket: 'flutterpushnotification-2ebe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHDwLfXJnbfjDjDw7V2fruifFLG4s7KLY',
    appId: '1:379044413189:ios:d9ac47cdde3b687959c16c',
    messagingSenderId: '379044413189',
    projectId: 'flutterpushnotification-2ebe9',
    storageBucket: 'flutterpushnotification-2ebe9.appspot.com',
    iosBundleId: 'com.example.smesterproject',
  );
}
